// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package mqtt

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigDestinationConfigParam = "destinationConfigParam"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigDestinationConfigParam: {
			Default:     "yes",
			Description: "DestinationConfigParam must be either yes or no (defaults to yes).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"yes", "no"}},
			},
		},
	}
}
